/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PageBImport } from './routes/pageB'
import { Route as PageAImport } from './routes/pageA'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PageBRoute = PageBImport.update({
  path: '/pageB',
  getParentRoute: () => rootRoute,
} as any)

const PageARoute = PageAImport.update({
  path: '/pageA',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/pageA': {
      preLoaderRoute: typeof PageAImport
      parentRoute: typeof rootRoute
    }
    '/pageB': {
      preLoaderRoute: typeof PageBImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  PageARoute,
  PageBRoute,
])

/* prettier-ignore-end */
